imssopeonow/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('inventory.urls')),
    path("orders/",include('orders.urls')),
    path("transactions/",include('transactions.urls')),
    path("management/",include('management.urls')),
]

orders/urls.py
from django.urls import path
# from django.conf.urls import url

from . import views
urlpatterns = [
    path("", views.Orders.as_view(),name="orders"),
    path("order/", views.CreateOrder,name="order"),
    path("received/", views.ReceivedList.as_view(),name="orders-received"),
    path("cancelled/", views.CancelledList.as_view(),name="orders-cancelled"),
    path("order/<id>", views.OrderSpecific,name="order-specific"),
    path("receive-confirmation/<id>",views.MarkReceived,name="receive-confirmation"),
    path("cancel-confirmation/<id>",views.MarkCancelled,name="cancel-confirmation"),
]

orders/models.py
from django.db import models
from django.urls import reverse
from inventory.models import Inventory

# Create your models here.

class Order(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    name = models.CharField(max_length=25)
    item = models.ForeignKey(Inventory,on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    cost = models.PositiveIntegerField()
    orderdttm = models.DateTimeField(auto_now_add = True)
    is_received = models.BooleanField(default=False)
    is_cancel = models.BooleanField(default=False)
    

    def __str__(self) -> str:
        return self.name
    
    

orders/forms.py
from django import forms
from .models import Order
  
  
# creating a form
class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        # fields = ["id","name","item","quantity"]
        fields = [
            "item","quantity"]
class OrderSpecificForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["quantity"]
        
class MarkReceivedForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = []

class MarkCancelledForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = []

orders/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from orders.models import Order
from django.views.generic.edit import CreateView, UpdateView
import random,string
from django.views.generic import ListView, DetailView
from inventory.models import Inventory
from .forms import MarkCancelledForm, MarkReceivedForm, OrderForm, OrderSpecificForm

def generate_random(length):
    return ''.join(
        random.choices(
            string.ascii_letters + string.digits,
            k=length
        )
    )

class Orders(ListView):
    model = Order
    template_name="orders/orders.html"


def CreateOrder(request):
    context={}
    
    form = OrderForm(request.POST or None)
       
    if form.is_valid():
        quantity = int(request.POST.get('quantity'))
        item_to_be_ordered = request.POST.get('item')
        item_name_to_be_ordered = Inventory.objects.filter(id=item_to_be_ordered).values_list('name', flat=True)[0]
        item_cost = int(Inventory.objects.filter(name=item_name_to_be_ordered).values_list('cost', flat=True)[0])
        bill = item_cost*quantity
        item_to_be_ordered = request.POST.get('item')
        
        
        instance = form.save(commit=False)
        instance.cost = bill

        while True:
            new_name = generate_random(8)
            duplicate_name = Inventory.objects.filter(name=new_name).values_list(flat=True)
            
            if len(duplicate_name)==0:
                instance.name = new_name
                break
        
        while True:
            new_id = random.randint(1,10**7)
            duplicate_id = Inventory.objects.filter(id=new_id).values_list(flat=True)
            if len(duplicate_id)==0:
                instance.id = new_id
                break
        instance.save()
        return HttpResponseRedirect(reverse("orders"))

    else:
        HttpResponse("<h2>Invalid Form Entries</h2>")

    context['form'] = form

    return render(request,"orders/order.html",context)



class ReceivedList(ListView):
    model = Order
    template_name="orders/received.html"

class CancelledList(ListView):
    model = Order
    template_name="orders/cancelled.html"

def OrderSpecific(request,id):

    context={}
    
    form = OrderSpecificForm(request.POST or None)
       
    if form.is_valid():
        quantity = int(request.POST.get('quantity'))
        item_name_to_be_ordered = Inventory.objects.filter(id=id).values_list('name', flat=True)[0]
        item_cost = int(Inventory.objects.filter(name=item_name_to_be_ordered).values_list('cost', flat=True)[0])
        bill = item_cost*quantity
        form.instance.item_id = str(id)
        
        instance = form.save(commit=False)
        instance.cost = bill
        while True:
            new_name = generate_random(8)
            duplicate_name = Inventory.objects.filter(name=new_name).values_list(flat=True)
            
            if len(duplicate_name)==0:
                instance.name = new_name
                break
        
        while True:
            new_id = random.randint(1,10**7)
            duplicate_id = Inventory.objects.filter(id=new_id).values_list(flat=True)
            if len(duplicate_id)==0:
                instance.id = new_id
                break
        instance.save()
        return HttpResponseRedirect(reverse("orders"))

    else:
        HttpResponse("<h2>Invalid Form Entries</h2>")

    context['form'] = form

    return render(request,"orders/order-specific.html",context)

def MarkReceived(request,id):
    context={}
    
    form = MarkReceivedForm(request.POST or None)
       
    if form.is_valid():
        
        
        item = Order.objects.get(id=id)
        #one way of updating db entry
        form.instance.item_id = item.item_id
        form.instance.name = item.name
        form.instance.quantity = item.quantity
        
        item_in_inventory = Inventory.objects.get(id=item.item_id)
        item_in_inventory.quantity+= item.quantity
        item_in_inventory.save()
        
        instance = form.save(commit=False)
        instance.id = str(id)
        instance.cost = item.cost
        instance.orderdttm = item.orderdttm
        instance.is_received = True
        
        instance.save()
        return HttpResponseRedirect(reverse("orders"))

    else:
        HttpResponse("<h2>Invalid Form Entries</h2>")

    context['form'] = form

    return render(request,"orders/receiveconfirm.html",context)

def MarkCancelled(request,id):
    context={}
    
    form = MarkCancelledForm(request.POST or None)
       
    if form.is_valid():
        
        
        item = Order.objects.get(id=id)

        form.instance.item_id = item.item_id
        form.instance.name = item.name
        form.instance.quantity = item.quantity
        
        instance = form.save(commit=False)
        instance.id = str(id)
        instance.cost = item.cost
        instance.orderdttm = item.orderdttm
        instance.is_cancel = True
        instance.save()
        return HttpResponseRedirect(reverse("orders"))

    else:
        HttpResponse("<h2>Invalid Form Entries</h2>")

    context['form'] = form

    return render(request,"orders/cancelconfirm.html",context)

templates/orders/cancelconfirm.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/items.css' %}">
</head>

<div id="items-main">
    
    <h1 id="items-title">Do you Want to Cancel the Order?</h1>     
    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="confirm" id="item-btn">Yes, Cancel</button>
    </form>
             
</div>

{% endblock %}

templates/orders/cancelled.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/items.css' %}">
</head>

<div id="items-main">
    <h1 id="items-title">Orders Cancelled</h1>
    

    <table id="item-table">
        <thead>
            <tr>
                <th>Order ID</th>
                <th>Order Name</th>
                <th>Item Code</th>
                <th>Quantity</th>
                <th>Cost</th>
                <th>Order Date and Time</th>
                
            </tr>
        </thead>
        
        <tbody>
            {% for item in order_list %}
                {% if item.is_cancel == 1  %}
                <tr id="item-entry">

                    <td>{{item.id}}</td>
                    <td>{{item.name}}</td>
                    <td>{{item.item_id}}</td>
                    <td>{{item.quantity}}</td>
                    <td>{{item.cost}}</td>
                    <td>{{item.orderdttm}}</td>
                    
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
        
    </table>
</div>

{% endblock %}

templates/orders/order-specific.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/order-specific.css' %}">
</head>

<div id="order-new-main">
    <form id="order-form" method="post">
        {% csrf_token %}
        {{form.as_p}}
        
        <input type="submit" value="Create Order">
    </form>
</div>

{% endblock %}

templates/orders/order.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/order-item.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" >  
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    <div id="order-new-main">
        <h1 id="add-new-title">Create Order</h1>

        <form id='order-form' method="post">
            {% csrf_token %}
            {{form.as_p}}
            
            <input id="order-btn" class="btn btn-primary" type="submit" value="Create Order">
        </form>
    </div>

    
    
</body>
</html>

{% endblock %}

templates/orders/orders.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/items.css' %}">
</head>

<div id="items-main">
    <h1 id="items-title">Orders</h1>
    

    <table id="item-table">
        <thead>
            <tr>
                <th>Order ID</th>
                <th>Order Name</th>
                <th>Item Code</th>
                <th>Quantity</th>
                <th>Cost</th>
                <th>Order Date and Time</th>
                <th>Status</th>
            </tr>
        </thead>
        
        <tbody>
            {% for item in order_list %}
                <tr id="item-entry">

                    <td>{{item.id}}</td>
                    <td>{{item.name}}</td>
                    <td>{{item.item_id}}</td>
                    <td>{{item.quantity}}</td>
                    <td>{{item.cost}}</td>
                    <td>{{item.orderdttm}}</td>

                    <td>{% if item.is_received == 0 and item.is_cancel == 0 %}                    
                        <a href="{% url 'receive-confirmation' item.id %}"><button id="item-btn">Received?</button></a>

                        <a href="{% url 'cancel-confirmation' item.id %}"><button id="item-btn">Cancel Order</button></a>
                        {% elif item.is_received == 1 %}
                            Received
                        {% elif item.is_cancel == 1 %}
                            Cancelled
                    {% endif %}</td>
                    
                </tr>
            {% endfor %}
        </tbody>
        
    </table>
</div>

{% endblock %}

templates/orders/receiveconfirm.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/items.css' %}">
</head>

<div id="items-main">
    
    <h1 id="items-title">Have You Received the Order?</h1>     
    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="confirm" id="item-btn">Yes, Received</button>
    </form>
             
</div>

{% endblock %}

templates/orders/received.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/items.css' %}">
</head>

<div id="items-main">
    <h1 id="items-title">Orders Received</h1>
    <table id="item-table-received">
        <thead>
            <tr>
                <th>Order ID</th>
                <th>Order Name</th>
                <th>Item Code</th>
                <th>Quantity</th>
                <th>Cost</th>
                <th>Order Date and Time</th>
                
            </tr>
        </thead>
        
        <tbody>
            {% for item in order_list %}
                {% if item.is_received == 1  %}
                <tr id="item-entry">

                    <td>{{item.id}}</td>
                    <td>{{item.name}}</td>
                    <td>{{item.item_id}}</td>
                    <td>{{item.quantity}}</td>
                    <td>{{item.cost}}</td>
                    <td>{{item.orderdttm}}</td>
                    
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
        
    </table>

    
</div>

{% endblock %}