imssopeonow/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('inventory.urls')),
    path("orders/",include('orders.urls')),
    path("transactions/",include('transactions.urls')),
    path("management/",include('management.urls')),
]

orders/urls.py
from django.urls import path
# from django.conf.urls import url

from . import views
urlpatterns = [
    path("", views.Orders.as_view(),name="orders"),
    path("order/", views.CreateOrder,name="order"),
    path("received/", views.ReceivedList.as_view(),name="orders-received"),
    path("cancelled/", views.CancelledList.as_view(),name="orders-cancelled"),
    path("order/<id>", views.OrderSpecific,name="order-specific"),
    path("receive-confirmation/<id>",views.MarkReceived,name="receive-confirmation"),
    path("cancel-confirmation/<id>",views.MarkCancelled,name="cancel-confirmation"),
]

transactions/urls.py
from django.urls import path
from .views import *

urlpatterns=[
    path("",Transactions.as_view(),name='transactions'),
    path("sell/", CreateTransaction,name="sell"),
    path("sell/<id>", TransactSpecific,name="sell-specific"),
]

transactions/models.py
from django.db import models
from inventory.models import Inventory
# Create your models here.

class Transactions(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=25)
    item = models.ForeignKey(Inventory,on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    selling_price = models.IntegerField()
    transactiondttm = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name

transactions/forms.py
from django import forms
from .models import Transactions


class SellForm(forms.ModelForm):
    class Meta:
        model = Transactions
        fields = ["item","quantity"]
        
class SellSpecificForm(forms.ModelForm):
    class Meta:
        model = Transactions
        fields = ["quantity"]

transactions/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import ListView
from inventory.models import Inventory
from transactions.forms import SellForm, SellSpecificForm
from .models import Transactions
# Create your views here.
import random,string

def generate_random(length):
    return ''.join(
        random.choices(
            string.ascii_letters + string.digits,
            k=length
        )
    )

class Transactions(ListView):
    model = Transactions
    template_name="transactions/transactions.html"

    

def CreateTransaction(request):
    context={}
    
    form = SellForm(request.POST or None)

    if form.is_valid():
        quantity = int(request.POST.get('quantity'))
        item_to_be_ordered = request.POST.get('item')
        item_name_to_be_ordered = Inventory.objects.filter(id=item_to_be_ordered).values_list('name', flat=True)[0]
        item_cost = int(Inventory.objects.filter(name=item_name_to_be_ordered).values_list('selling_price', flat=True)[0])
        bill = item_cost*quantity
        item_to_be_ordered = request.POST.get('item')
        in_stock = Inventory.objects.filter(id=item_to_be_ordered).values_list('quantity',flat=True)[0]
        # print(item_name_to_be_ordered)
        form.instance.selling_price = item_cost*quantity
        if in_stock<quantity:
            return HttpResponse("Maximum quantity available: "+str(in_stock))
        item = Inventory.objects.get(id=item_to_be_ordered)
        item.quantity = in_stock-quantity
        item.quantity_sold = quantity
        item.profit_earned = item.quantity_sold*(item.selling_price-item.cost)
        item.save()
        
        instance = form.save(commit=False)
        instance.cost = bill

        while True:
            new_name = generate_random(8)
            duplicate_name = Inventory.objects.filter(name=new_name).values_list(flat=True)
            
            if len(duplicate_name)==0:
                instance.name = new_name
                break
        
        while True:
            new_id = random.randint(1,10**7)
            duplicate_id = Inventory.objects.filter(id=new_id).values_list(flat=True)
            if len(duplicate_id)==0:
                instance.id = new_id
                break

        instance.save()
        return HttpResponseRedirect(reverse("transactions"))

    else:
        HttpResponse("<h2>Invalid Form Entries</h2>")

    context['form'] = form

    return render(request,"transactions/sell.html",context)

def TransactSpecific(request,id):
    context={}
    
    form = SellSpecificForm(request.POST or None)
       
    if form.is_valid():
        quantity = int(request.POST.get('quantity'))
        item_name_to_be_ordered = Inventory.objects.filter(id=id).values_list('name', flat=True)[0]
        item_cost = int(Inventory.objects.filter(name=item_name_to_be_ordered).values_list('selling_price', flat=True)[0])
        bill = item_cost*quantity
        form.instance.item_id = str(id)
        in_stock = Inventory.objects.filter(id=id).values_list('quantity',flat=True)[0]
        if in_stock<quantity:
            return HttpResponse("Maximum quantity available: "+str(in_stock))
        item = Inventory.objects.get(id=id)
        item.quantity = in_stock-quantity
        item.quantity_sold = quantity
        
        item.profit_earned = item.quantity_sold*(item.selling_price-item.cost)
        item.save()
        instance = form.save(commit=False)
        instance.selling_price = bill
        
        while True:
            new_name = generate_random(8)
            duplicate_name = Inventory.objects.filter(name=new_name).values_list(flat=True)
            
            if len(duplicate_name)==0:
                instance.name = new_name
                break
        
        while True:
            new_id = random.randint(1,10**7)
            duplicate_id = Inventory.objects.filter(id=new_id).values_list(flat=True)
            if len(duplicate_id)==0:
                instance.id = new_id
                break
    
        instance.save()
        return HttpResponseRedirect(reverse("transactions"))

    else:
        HttpResponse("<h2>Invalid Form Entries</h2>")

    context['form'] = form

    return render(request,"transactions/sell-specific.html",context)

templates/transactions/sell-specific.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/sell-specific.css' %}">
</head>

<div id="sell-new-main">
    <form id="sell-form" method="post">
        {% csrf_token %}
        {{form.as_p}}
        
        <input type="submit" value="Sell">
    </form>
</div>

{% endblock %}

templates/transactions/sell.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/sell-item.css' %}">
</head>
<body>
    <div id="sell-new-main">
        <h1 id="add-new-title">Sell Item</h1>

        <form id="sell-form" method="post">
            {% csrf_token %}
            {{form.as_table}}
            
            <input id="sell-btn" type="submit" value="Sell">
        </form>
    </div>

    
    
</body>
</html>

{% endblock %}

templates/transactions/transactions.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/items.css' %}">
</head>

<div id="items-main">
    <h1 id="items-title">Transactions</h1>
    

    <table id="transaction-table">
        <thead>
            <tr>
                <th>Order ID</th>
                <th>Order Name</th>
                <th>Item Code</th>
                <th>Quantity</th>
                <th>Cost</th>
                <th>Transaction Date and Time</th>
                
            </tr>
        </thead>
        
        <tbody>
            {% for item in transactions_list %}
                <tr id="item-entry">

                    <td>{{item.id}}</td>
                    <td>{{item.name}}</td>
                    <td>{{item.item_id}}</td>
                    <td>{{item.quantity}}</td>
                    <td>{{item.selling_price}}</td>
                    <td>{{item.transactiondttm}}</td>

                    <td>{% if item.is_received == 0 and item.is_cancel == 0 %}                    
                        <a href="{% url 'receive-confirmation' item.id %}"><button id="item-btn">Received?</button></a>

                        <a href="{% url 'cancel-confirmation' item.id %}"><button id="item-btn">Cancel Order</button></a>
                        {% elif item.is_received == 1 %}
                            Received
                        {% elif item.is_cancel == 1 %}
                            Cancelled
                    {% endif %}</td>
                    
                </tr>
            {% endfor %}
        </tbody>
        
    </table>
</div>

{% endblock %}